# Generated by Django 4.0.2 on 2022-03-24 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='id',
        ),
        migrations.AlterField(
            model_name='label',
            name='label_index',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='标签索引'),
        ),
        migrations.AlterField(
            model_name='log',
            name='file_path',
            field=models.FileField(upload_to='', verbose_name='文件地址'),
        ),
        migrations.AlterUniqueTogether(
            name='live',
            unique_together={('user', 'link')},
        ),
        migrations.AlterUniqueTogether(
            name='log',
            unique_together={('user', 'created_time')},
        ),
        migrations.AlterUniqueTogether(
            name='push',
            unique_together={('user', 'corp_id')},
        ),
    ]
